# -*- coding: utf-8 -*-
"""train_inceptionv3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NzXABQUJvta9XLOrZRmvbdCPI7tZxWO
"""

from fastai.vision.all import *
import timm

def train_model(dls, model_name='inception_v3.tf_in1k', pretrained=True):
    metrics = [
        accuracy,
        Precision(average='macro'),
        Recall(average='macro'),
        F1Score(average='macro'),
        RocAucBinary()
    ]

    learn = vision_learner(
        dls,
        model_name,
        metrics=metrics,
        loss_func=CrossEntropyLossFlat(),
        pretrained=pretrained
    ).to_fp16()

    return learn