# -*- coding: utf-8 -*-
"""train_mobilenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W28J7KvnT0y9nD97l14E1ei7IivGPHhT
"""

from fastai.vision.all import *
import timm

def train_model(dls, model_name='mobilenetv5_base', pretrained=True):
    metrics = [
        accuracy,
        Precision(average='macro'),
        Recall(average='macro'),
        F1Score(average='macro'),
        RocAucBinary()
    ]

    learn = vision_learner(
        dls,
        model_name,
        metrics=metrics,
        loss_func=CrossEntropyLossFlat(),
        pretrained=pretrained
    ).to_fp16()

    return learn