# -*- coding: utf-8 -*-
"""train_efficientvit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18c3MOAN8J1N_B0XUnefC_VNZOGGCMy-Q
"""

from fastai.vision.all import *
import timm

def train_model(dls, model_name='efficientvit_m5.r224_in1k', pretrained=True):
    metrics = [
        accuracy,
        Precision(average='macro'),
        Recall(average='macro'),
        F1Score(average='macro'),
        RocAucBinary()
    ]

    learn = vision_learner(
        dls,
        model_name,
        metrics=metrics,
        loss_func=CrossEntropyLossFlat(),
        pretrained=pretrained
    ).to_fp16()

    return learn